# storage k liye persistent volume and persistent volume claim use hota hai.
# 3 step process - create PV, claim PV(or create PVC), create deployments in the same namespace. if namespaces are different then the vol bind won'y work
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx
  labels:
    app: local
spec:
  capacity:
    # storage nikal diya 1 Gi ka 30gb se
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # retain the data after delete the pod
  persistentVolumeReclaimPolicy: Retain
  # storage class - local-storage, cloud-storage
  storageClassName: local-storage
  # host pr storage ki location
  hostPath:

    path: /mnt/data
