apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  tolerations:
      # yha pr key daal do like pod=true. kyuki taint krte time thi key di thi
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
