apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:

  containers:

  # Main app container
  - name: app
    image: nginx
    ports:
    - containerPort: 80

  # Sidecar container (runs parallel)
  - name: log-agent
    image: busybox
    command: ['sh', '-c', 'while true; do echo logging...; sleep 5; done']
