# you can create it on kind only. 
# apply this first - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
#
# now create this cluster role. ns, role and somethings are created in this before hand
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: admin-user
  namespace: kubernetes-dashborad
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-binding
    # this namespace created on first apply
  namespace: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: kubernetes-dashboard
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
# further run these
# kubectl -n kubernetes-dashboard create token admin-user
# kubectl proxy --port=8081 --address=0.0.0.0 --accept-hosts='.*'
# http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
# enter the token and you can see the dashboard
