# cmd - kubectl get pods
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apche-manager
  namespace: apache
rules:
  # api version dalega api group main - like v1, apps/v1, batch/v1
  - apiGroups: 
      - "" 
      - apps 
      - rbac.authorization.k8s.io
      - batch
    # resource matlab / ke baad wala - like apps ke liye v1, "" ke liye v1, deployment, namespace etc
    resources: 
      - deployment
      - pod
      - service
    # verbs main action -like get ,apply , delete etc
    verbs: 
      - get
      - apply
      - delete 
      - watch
      - create 
      - patch	
