apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: apache

spec:
  scaleTargetRef:
    # yha btao kise scale krne ka deployment service yaa kuch or
    kind: Deployment
    name: apache-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3 
  # metrics here
  metrics:
    - type: Resource
      name: cpu
      target:
        type: Utilization
        # average utilization cpu percent
        averageUtilization: 5
